### PR TITLE
New README.md for clarity

### PR DESCRIPTION
**Pull request by seanonthenet**
Hi guys. 
I spent a ton of time rewriting and working on the README for GraphQL Zeus. Mainly because I **love** the package, use it heavily and I want **as many devs as possible** to take it up and contribute and make it better and support it. And in so doing draw attention to GraphQL Editor too.

Previously I would refer friends and colleagues to the package and they would have a difficult time understanding how the package worked and how it would fit into their stack and workflow from the README. I've rewritten and re-organised it to be as clear as possible without completely getting rid of the original content. 

You'll also notice that I had a designer work on the logo. This is because the original looked bad on dark mode on GitHub and also so that it would fit in more with GraphQL itself and the feel of GraphQL Editor. I have the file for the new logo in Figma and please feel free to make changes or let me know if you would like any changes. https://www.figma.com/file/d08GJKuHN8dKzSvOxDKMaJ/New-GraphQL-Zeus-Logo 

Hope you guys like it. If you would like anything else changed please let me know and I'll handle it.

### CODE REVIEW

**Comment by seanonthenet** [comment]
Just noticed a missed space after a the `## Usage Example` heading which I'll fix on another PR. :)

**Comment by seanonthenet** [comment]
Also just noticed the Slack link is broken :/

**Review by aexol — APPROVED** [review]

**Comment by aexol** [comment]
Thanks man! I will deploy docs out of it today. For better readability

**Comment by aexol** [comment]
https://zeus.graphqleditor.com/

**Comment by aexol** [comment]
new logo looks cool

**Comment by seanonthenet** [comment]
Awesome!!
New docs pages look so good! 
Is there a new invite link for the Slack channel? Current one is broken

**Pull request merged**
