### PR TITLE
bugfix: Added fetch and websockets imports for node environments.

### PR DESCRIPTION
**Pull request by nikodevv**
Adds missing imports for node environment. 
Related to https://github.com/graphql-editor/graphql-zeus/issues/226

### CODE REVIEW

**Comment by nikodevv** [comment]
Our team would love to use `graphgql-zeus`, but we would prefer not to maintain a separate fork. This is one of the main bugs preventing us adopting the library.

**Comment by JonahElbaz** [comment]
Would love to see this ASAP!

**Comment by tomhirschfeld** [comment]
👍

**Comment by dannybpw** [comment]
👍

**Review by aexol — APPROVED** [review]

**Pull request merged**
