### PR TITLE
fix:346 Error encoding arrays of custom scalars 

### PR DESCRIPTION
**Pull request by Vishal-Sikka**
code has been adjusted to handle arrays of custom scalar types 

fix: #346
/claim #346

### CODE REVIEW

**Comment by aexol** [comment]
No way, this is not the correct approach. You should not seek for the UUID but make it work for all the custom scalars with array

**Comment by Vishal-Sikka** [comment]
> No way, this is not the correct approach. You should not seek for the UUID but make it work for all the custom scalars with array

adjusted  code to handle arrays of custom scalar types

**Comment by aexol** [comment]
Ok, there is even no mock no nothing, so you are testing against schema which doesn't have the so called scalar? Closing

**Comment by Vishal-Sikka** [comment]
> Ok, there is even no mock no nothing, so you are testing against schema which doesn't have the so called scalar? Closing

i have tested what user had issue with, i could have got more clarification if you have defined specific requirements, just read user's issue on #346 with point of view of some on is non graphql-zeus user , probably you should create new issue with proper details

**Comment by akansh-bansal** [comment]
i want to pick it up @aexol could you clarify your requirements ?

**Pull request closed without merging**
