### PR TITLE
[##Fix: Document Site LHS menu scroll is fix]

### PR DESCRIPTION
**Pull request by kavin-monarch**

### CODE REVIEW

**Comment by kavin-monarch** [comment]
image
Unable to scroll lhs menu in document site

**Comment by joserocha3** [comment]
Hi @kavin-monarch, you need to run `yarn style` to update the `tw.css` file, or `overflow-y-auto` will not exist.

**Comment by kavin-monarch** [comment]
@joserocha3 I am having a setup issue with purplehaze when run npm start puppeter chromium issue
```
[0] 
[0] > graphql-zeus-doc@1.0.0 dev
[0] > purplehaze
[0] 
[1] 
[1] > graphql-zeus-doc@1.0.0 style
[1] > tailwindcss -i ./input.css -o ./src/tw.css --watch
[1] 
[1] 
[1] Rebuilding...
[1] Done in 149ms.
[0] graphql-zeus/doc/node_modules/.pnpm/puppeteer@8.0.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193
[0]             reject(new Error([
[0]                    ^
[0] 
[0] Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT
[0] 
[0] 
[0] TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
[0] 
[0]     at onClose (graphql-zeus/doc/node_modules/.pnpm/puppeteer@8.0.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
[0]     at ChildProcess.<anonymous> (graphql-zeus/doc/node_modules/.pnpm/puppeteer@8.0.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
[0]     at ChildProcess.emit (node:events:527:28)
[0]     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
[0]     at onErrorNT (node:internal/child_process:478:16)
[0]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[0] npm run dev exited with code 1

```

**Comment by joserocha3** [comment]
@kavin-monarch looks like it is having trouble finding `chromium-browser` -> `ENOENT`(Error NO ENTry). Maybe it was installed on my machine when I installed puppeteer? @aexol might be able to help you more than I can.

**Pull request closed without merging**
